lab-srs/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :reports
  get 'home/about'
  root 'reports#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # get '/posts', to: 'posts#index'
  
  # get '/posts/:id', to: 'posts#show'
  
  # get '/posts/new', to: 'posts#new'
  
  # post '/posts', to: 'posts#create'
  
  # get '/posts/:id/edit', to: 'posts#edit'
  
  # put '/posts/:id', to: 'posts#update'
  
  # delete '/posts/:id', to: 'posts#destroy'

end

lab-srs/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lab-srs/app/models/report.rb
class Report < ApplicationRecord
    include ActiveModel::Validations
    belongs_to :user
    validates :title, length: {maximum: 250 }, presence: true
    validates :description, length: { maximum: 500 }, presence: true
    validate :correct_range

    def user_data
        User.find(self.user_id).formatted_name
    end

    def correct_range 
        if grade.to_i > 100 or grade.to_i < 0
            errors.add(:grade, 'should be in range 0..100')
        end
    end
end

lab-srs/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :reports
    validates :first_name, length: { maximum: 100 }
    validates :last_name, length: { maximum: 100 }
    validates :email, length: { maximum: 150 }, format: { with: URI::MailTo::EMAIL_REGEXP }

    def formatted_name
        "#{first_name} #{last_name} #{email}"
    end
end

lab-srs/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    private
  
    def require_login
      unless user_signed_in?
        flash[:error] = "You must be logged in to access this section"
        authenticate_user!
        # redirect_to new_user_session_path
      end
    end
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :first_name, :last_name])
    end
  
    def after_sign_out_path_for(resourse_or_scope)
      request.referrer
    end
  end

lab-srs/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
  
    def about
    end
  
  end

lab-srs/app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: %i[ show edit update destroy ]

  # GET /reports or /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1 or /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports or /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: "Report was successfully created." }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1 or /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: "Report was successfully updated." }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1 or /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: "Report was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      params.require(:report).permit(:user_id, :title, :description, :grade)
    end
end

lab-srs/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name)
    end
end

lab-srs/app/helpers/application_helper.rb
module ApplicationHelper
end

lab-srs/app/helpers/reports_helper.rb
module ReportsHelper
end

lab-srs/app/helpers/users_helper.rb
module UsersHelper
end

lab-srs/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Lab Reports', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Reports', reports_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add report', new_report_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add user', new_user_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Users', users_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

lab-srs/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <title>Labs reports</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

  <%= render 'home/header'  %>
  <div class="container">
    <br/>
    <%= yield %>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

lab-srs/app/views/reports/_form.html.erb
<%= form_with(model: report) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>
      
      <ul>
        <% report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field form-group">
    <% form.label :user_id %>
    <div>
      <%= form.collection_select :user_id, User.all, :id, :formatted_name, {:prompt=>true}, {:class=>"form-select"}  %>
    </div>
  </div>
  <br>
  <div class="field form-group">
    <% form.label :title %>
    <%= form.text_field :title, class: "form-control", placeholder: "Title", required: true %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.text_area :description, class: "form-control", placeholder: "Description", required: true %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit 'Save',class: "btn btn-outline-dark" %>
  </div>
<% end %>

lab-srs/app/views/reports/_report.html.erb
<div id="<%= dom_id report %>" class="scaffold_record">
  <p>
    <strong>User:</strong>
    <%= report.user_id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= report.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= report.description %>
  </p>

  <p>
    <strong>Grade:</strong>
    <%= report.grade %>
  </p>
</div>

lab-srs/app/views/reports/edit.html.erb
<h1 align="center">Mark</h1>

<%= form_with(model: @report) do |form| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% @report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field form-group" align="center">
    <%= form.text_field :grade, class: "form-control", placeholder: "Mark", require: '0'..'100' %>
  </div>

  <br/>
  <div class="actions" align="center">
    <%= form.submit "Save", class: "btn btn-outline-dark"%>
  </div>
<% end %>

lab-srs/app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Labs Reports</h1>
<%= link_to "New report", new_report_path, class:"btn btn-outline-dark" %>
<br/><br/>
<% @reports.each do |report| %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= report.title %></h5>
      <h6 class="card-subtitle mb-2 text-muted">User: <%= report.user_data %></h6>
      <p class="card-text"><%= report.description %></p>
      <% if !report.grade.blank? %>
        <p class="card-text" style="float: left; width: 100px; padding-top: 5px">
          Mark:
          <% case (report.grade.to_i)%>
          <% when 95..100 %>
            <%= 'A' %>
          <% when 86..94 %>
            <%= 'B' %>
          <% when 69..85 %>
            <%= 'C' %>
          <% when 61..68 %>
            <%= 'D' %>
          <% when 51..60 %>
            <%= 'E' %>
          <% when 31..50 %>
            <%= 'FX' %>
          <% when 0..30 %>
            <%= 'F' %>
          <% else %>
          <%= puts('No') %>
            <% end %>
          (<%= report.grade %>)
        </p>

      <% else %>
          <div style="float: left; width: 115px">
            <%= link_to 'Add mark', edit_report_path(report), class:"btn btn-outline-dark" %>
          </div>
      <% end %>
        <div style="float: left; width: 80px">
          <%= link_to "Show", report, class:"btn btn-outline-dark" %>
        </div>
        <div style="float: left">
          <%= button_to "Remove", report, method: :delete, data: {confirm: "Are you sure you want to reset the indexes?" }, class:"btn btn-outline-dark" %>
        </div>
    </div>
  </div>
  <br/>
<% end %>
<br/>

lab-srs/app/views/reports/new.html.erb
<h1>New report</h1>

<%= render "form", report: @report %>

<br>

lab-srs/app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @report %>

<div>
  <%= link_to "Edit this report", edit_report_path(@report), class:"btn btn-outline-dark" %> | 
  <%= link_to "Back to reports", reports_path, class:"btn btn-outline-dark" %>
  <br/><br/>
  <%= button_to "Destroy this report", report_path(@report), method: :delete, class:"btn btn-outline-dark" %>
</div>

lab-srs/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>
  <br/>
  <div class="actions">
    <%= form.submit 'Save', class: "btn btn-outline-dark" %>
  </div>
<% end %>

lab-srs/app/views/users/_user.html.erb
<div id="<%= dom_id user %>" class="scaffold_record">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>
</div>

lab-srs/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

lab-srs/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Users</h1>
<%= link_to "New user", new_user_path, class:"btn btn-outline-dark" %>
<br/><br/>
<% @users.each do |user| %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-subtitle">
        <div>
          <sub class="text-muted"><%= user.email %></sub>
        </div>
        <%= user.first_name %> <%= user.last_name %>
      </h5> 
        <div style="float: left; width: 80px; padding-top:10px">
          <%= link_to "Show", user, class:"btn btn-outline-dark" %>
        </div>
    </div>
  </div>
  <br/>
<% end %>

lab-srs/app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", reports_path, class:"btn btn-outline-dark" %>
</div>

lab-srs/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user), class:"btn btn-outline-dark" %> |
  <%= link_to "Back to users", users_path, class:"btn btn-outline-dark" %>
  <br/><br/>
  <%= button_to "Destroy this user", user_path(@user), method: :delete, class:"btn btn-outline-dark" %>
</div>